project:
  type: website

website:
  title: "NoteSite"
  sidebar:
    - title: "Econometrics"
      contents: "notes/econometrics"
    - title: "Micro/Macro"
      contents: "notes/micro-macro"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    execute:
      echo: false

editor: source

